
test-mode: true
print-passwords: false

git:
  base-path: '~/Desktop/example'
  username: 'my-git-user'
  password: 'my-git-password'
  merge-message: 'Merge branch ''#[SOURCE_BRANCH]'' into ''#[TARGET_BRANCH]'' (auto-merge)'
  timeout-milliseconds: 5000
  
jenkins:
  base-url: 'http://myjenkins.com'
  crumb-url: '/crumbIssuer/api/json'
  username: 'my-jenkins-user'
  password: 'my-jenkins-password'
  insecure-https: false
  timeout-milliseconds: 5000

maven:
  maven-home-folder: '/Library/apache-maven-3.6.3'
  base-path: '~/Desktop/example'

action-definitions:
  -
    name: 'My Define Vars Action'
    type: 'DEFINE_VARIABLES'
    variables:
      my-first-var: 'my-fixed-value'
      my-second-var: '{ask-me}'
  -
    name: 'My Jenkins Action'
    type: 'JENKINS_BUILD'
    url: '/my-build/url'
    parameters:
      my-first-param: 'sample'
      my-second-param: '{ask-me,remove-whitespace}'
      my-third-param: 'Variable replacement #[my-first-var]'
  -
    name: 'My Merges Action'
    type: 'GIT_MERGES'
    repository-folder: '/my-folder'
    merges:
      -
        source-branch: 'my-branch'
        target-branch: '{ask-me,remove-whitespace}'
        pull: true
      -
        source-branch: 'this-branch'
        target-branch: 'that-branch'
        pull: false
  -
    name: 'My Maven Action'
    type: 'MAVEN_COMMANDS'
    project-folder: '/my-folder/project'
    commands:
      -
        goals: 'versions:set'
        offline: true
        arguments:
          newVersion: '#[my-second-var]'
          generateBackupPoms: 'false'
      -
        goals: 'clean install'
        suppress-output: true
    git-commit:
      branch: 'my-branch'
      pull: true
      commit-message: 'My message with variable #[my-second-var]'
  -
    name: 'My Operating System Action'
    type: 'OPERATING_SYSTEM_COMMANDS'
    folder: '~/Desktop/other-folder'
    commands:
      -
        command: 'echo "New date:" $(date +%F-%T) >> date.txt'
        suppress-output: false
    git-commit:
      branch: 'my-branch'
      pull: false
      commit-message: 'Date update'
  -
    name: 'My Wait Action'
    type: 'WAIT'
    wait-time-milliseconds: 5000
    manual-wait-prompt: 'Are you sure you want to proceed'
  -
    name: 'My Chain Action'
    type: 'CHAIN'
    actions:
      - 'My Jenkins Action'
      - 'My Merges Action'
      - 'My Maven Action'

categories:
  -
    name: 'My First Category'
    projects:
      -
        name: 'My First Project'
        action-names:
          - 'My Define Vars Action'
          - 'My Jenkins Action'
      -
        name: 'My Second Project'
        action-names:
          - 'My Define Vars Action'
          - 'My Merges Action'
          - 'My Maven Action'
      -
        name: 'My Third Project'
        action-names:
          - 'My Wait Action'
          - 'My Operating System Action'
  -
    name: 'My Second Category'
    projects:
      -
        name: 'My Fourth Project'
        action-names:
          - 'My Define Vars Action'
          - 'My Chain Action'
