
test-mode: true
print-passwords: false

git:
  base-path: '~/Desktop/example'
  username: 'my-git-user'
  password: 'my-git-password'
  merge-message: 'Merge branch ''#[SOURCE_BRANCH]'' into ''#[TARGET_BRANCH]'' (auto-merge)'
  timeout-milliseconds: 5000
  
jenkins:
  base-url: 'http://myjenkins.com'
  crumb-url: '/crumbIssuer/api/json'
  username: 'my-jenkins-user'
  password: 'my-jenkins-password'
  insecure-https: false
  timeout-milliseconds: 5000

maven:
  maven-home-folder: '/Library/apache-maven-3.6.3'
  base-path: '~/Desktop/example'

action-definitions:
  -
    name: 'My Define Vars Action'
    type: 'DEFINE_VARIABLES'
    variables:
      -
        key: 'my-first-var'
        value: 'my-fixed-value'
      -
        key: 'my-second-var'
        ask-me: true
  -
    name: 'My Jenkins Action'
    type: 'JENKINS_BUILD'
    url: '/my-build/url'
    parameters:
      -
        key: 'my-first-param'
        value: 'sample'
      -
        key: 'my-second-param'
        ask-me: true
      -
        key: 'my-third-param'
        value: 'Variable replacement #[my-first-var]'
  -
    name: 'My Merges Action'
    type: 'GIT_MERGES'
    repository-folder: '/my-folder'
    merges:
      -
        source-branch: 'my-branch'
        target-branch: 'other-branch'
        pull: true
      -
        source-branch: 'this-branch'
        target-branch: 'that-branch'
        pull: false
  -
    name: 'My Maven Action'
    type: 'MAVEN_COMMANDS'
    project-folder: '/my-folder/project'
    commands:
      -
        goals: 'versions:set'
        arguments:
          -
            key: 'newVersion'
            value: '#[my-second-var]'
          -
            key: 'generateBackupPoms'
            value: 'false'
      -
        goals: 'clean install'
        print-maven-output: true
    git-commit:
      branch: 'my-branch'
      pull: true
      commit-message: 'My message with variable #[my-second-var]'
  -
    name: 'My Chain Action'
    type: 'CHAIN'
    actions:
      - 'My Jenkins Action'
      - 'My Merges Action'
      - 'My Maven Action'

categories:
  -
    name: 'My First Category'
    projects:
      -
        name: 'My First Project'
        action-names:
          - 'My Define Vars Action'
          - 'My Jenkins Action'
      -
        name: 'My Second Project'
        action-names:
          - 'My Define Vars Action'
          - 'My Merges Action'
          - 'My Maven Action'
  -
    name: 'My Second Category'
    projects:
      -
        name: 'My Third Project'
        action-names:
          - 'My Define Vars Action'
          - 'My Chain Action'
